name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publishing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.10
      - run: bun install
      - run: bun run build
      - name: Publish
        run: bun publish -p --access public
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
